api_version = "unstable"

[[extensions]]
name = "GLS"
handle = "GLS"

uid = "ed1be157-e016-ea8f-f2ae-0bf791cc5b2c514610e7"

type = "function"


  [[extensions.targeting]]
  target = "purchase.pickup-point-delivery-option-generator.fetch"
  input_query = "src/fetch.graphql"
  export = "fetch"

  [[extensions.targeting]]
  target = "purchase.pickup-point-delivery-option-generator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
